export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';

export const TEST_ITEMS_LOADING = 'TEST_ITEMS_LOADING';
export const TEST_ITEMS_LOAD_SUCCESS = 'TEST_ITEMS_LOAD_SUCCESS';
export const TEST_ITEMS_LOAD_FAIL = 'TEST_ITEMS_LOAD_FAIL';
export const TEST_ITEMS_SET_SELECTED = 'TEST_ITEMS_SET_SELECTED';
export const TEST_ITEMS_DELETE = 'TEST_ITEMS_DELETE';

// User
export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_LOADING = 'LOGIN_LOADING';

export const REGISTRATION_LOADING = 'REGISTRATION_LOADING';
export const REGISTRATION_SUCCESSFUL = 'REGISTRATION_SUCCESSFUL';
export const REGISTRATION_FAIL = 'REGISTRATION_FAIL';